### ISSUE TITLE
Hmmmmmmmmmmm

### ISSUE THREAD

**Issue by Broquess** [Phongvngg1/Broque-Ramdisk#1]
Can you tell me the reason for unpacking my tool? i worked hard on this tool and you just unpack and post it here. Great

**Comment by Phongvngg1** [comment]
just for education and exploring code

**Comment by Broquess** [comment]
Did you ask permission from me?

**Comment by Phongvngg1** [comment]
bypassing is also illegal when you support illegal stuff like stealing device, we do illegal stuffs

**Comment by iiNexure** [comment]
lmaooo hardest reply I've ever seen
